const seedData = () => {
  return [
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Bussiness",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Bussiness",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },

    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Design",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
    {
      imageThumbnail: "https://bom.so/vV4j7x",
      topic: "Development",
      title: "Machine Learning A-Z™: Hands-On Python & R In Data...",
      rating: 5,
      views: 3000,
      price: 200,
    },
  ];
};

export default seedData;
